controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    arm_controller:
      type: position_controllers/JointGroupPositionController

    gripper_controller:
      type: position_controllers/JointGroupPositionController


mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: wheel_left_front_joint
    front_right_wheel_command_joint_name: wheel_right_front_joint
    rear_left_wheel_command_joint_name: wheel_left_back_joint
    rear_right_wheel_command_joint_name: wheel_right_back_joint

    kinematics:
      wheels_radius: 0.0678
      sum_of_robot_center_projection_on_X_Y_axis: 0.2096
      base_frame_offset:
        x: 0.0
        y: 0.0
        theta: 0.0

    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    tf_frame_prefix_enable: false
    reference_timeout: 2.0


arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5

    interface_name: position


gripper_controller:
  ros__parameters:
    joints:
      - r_joint

    interface_name: position
